stages:
  - deploy

deploy_docker_all:
  stage: deploy
  environment: production
  script:
      - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then TAG="latest"; else TAG="$CI_COMMIT_REF_NAME"; fi
      - if [ "$CI_PROJECT_NAMESPACE" = "anduin" ]; then HUB_NAMESPACE="anduin2019"; else HUB_NAMESPACE="$CI_PROJECT_NAMESPACE"; fi
      
      - LOCAL_TARGET_COM="hub.aiursoft.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG"
      - LOCAL_TARGET_CN="hub.aiursoft.cn/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG"
      - PUBLIC_TARGET="$HUB_NAMESPACE/$CI_PROJECT_NAME:$TAG"
      
      - echo "$LOCAL_DOCKER_PASSWORD" | docker login hub.aiursoft.com -u "$LOCAL_DOCKER_USERNAME" --password-stdin
      - echo "$CN_DOCKER_PASSWORD" | docker login hub.aiursoft.cn -u "$CN_DOCKER_USERNAME" --password-stdin
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      
      - docker buildx use aiur-global-builder
      - echo "Building and pushing multi-arch to all registries..."
      - |
          docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            -t $LOCAL_TARGET_COM \
            -t $LOCAL_TARGET_CN \
            -t $PUBLIC_TARGET \
            --push
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      exists:
        - Dockerfile